### ISSUE TITLE
I don't know where the key is?

### ISSUE THREAD

**Issue by ywsswy** [robbiev/two-factor-auth#9]
Warning: pasting the following URL into your browser exposes the OTP secret to Google:
  https://www.google.com/chart?chs=200x200&chld=M|0&cht=qr&chl=otpauth://totp/hill@VM_0_5_centos%3Fsecret%3DBNPOY5S6VK3A3ML4R4OYFFJW6E%26issuer%3DVM_0_5_centos
Your new secret key is: BNPOY5S6VK3A3ML4R4OYFFJW6E
Your verification code is 427203
Your emergency scratch codes are:
  30932611
  86577771
  96728177

[hill@TOVAOE2029 two-factor-auth]$ go run main.go BNPOY5S6VK3A3ML4R4OYFFJW6E
illegal base32 data at input byte 24
exit status 1

**Comment by robbiev** [comment]
Fixed in https://github.com/robbiev/two-factor-auth/pull/6
